### ISSUE TITLE
Spacing between icons in auto-complete

### ISSUE THREAD

**Issue by rwols** [AmjadHD/sublime_one_theme#1]
Congratulations, this is a pretty sweet theme.

There appears to be padding between the auto-complete icons for ST4. I think it would look better if that spacing wasn't there (or, whatever Atom does, since this theme apparently tries to port that).

<img width="614" alt="image" src="https://user-images.githubusercontent.com/2431823/105095882-92450580-5aa6-11eb-9f87-9dcfd783f9ad.png">

**Comment by AmjadHD** [comment]
> Congratulations, this is a pretty sweet theme.

Thanks 😊.

This is what I wasn't expecting, since I have no access to ST4, I had to copy and paste rules from the Adaptive theme hoping it'll go alright.

@rwols can you share a screenshot of the adaptive theme's autocompletion widget ?

**Comment by rwols** [comment]
This is Adaptive:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/2431823/105100782-1c449c80-5aae-11eb-880d-79d0c0538660.png">

**Comment by AmjadHD** [comment]
@rwols, I released a new version, it should be fixed now.

**Comment by rwols** [comment]
Looks like it is. Thanks!

<img width="614" alt="image" src="https://user-images.githubusercontent.com/2431823/105537979-0e338d80-5cf3-11eb-8c36-fc00600e4003.png">
