### ISSUE TITLE
File modify icon is missing

### ISSUE THREAD

**Issue by mstranger** [AmjadHD/sublime_one_theme#3]
Hi! 

Thanks for theme. 
For Sublime Text 3 there is no icon with information about modifying file. How can I get it back? 

![sample](https://user-images.githubusercontent.com/11062004/115895329-f808ab00-a462-11eb-9d15-8f11a3561cbe.png)

**Comment by AmjadHD** [comment]
> Thanks for theme.

you're welcomed 🙂 
> For Sublime Text 3 there is no icon with information about modifying file

you mean the tab close button when the file is dirty ?
make sure `highlight_modified_tabs` setting is set to `true` in your `Preferences.sublime-settings`.

**Comment by mstranger** [comment]
Yes, exactly. Thank you so much )
