### ISSUE TITLE
Active line highlight shows in quick panel and console in ST 4114

### ISSUE THREAD

**Issue by rwols** [AmjadHD/sublime_one_theme#4]
See screenshot

<img width="1680" alt="Schermafbeelding 2021-09-04 om 21 08 45" src="https://user-images.githubusercontent.com/2431823/132105495-abc2ee3f-2261-4a43-8421-7da4cc4122de.png">

**Comment by jfcherng** [comment]
https://github.com/sublimehq/sublime_text/issues/4805
