### ISSUE TITLE
Text in update dialog could use padding

### ISSUE THREAD

**Issue by rwols** [AmjadHD/sublime_one_theme#5]
One theme:

https://cdn.discordapp.com/attachments/280102180189634562/891253475822948392/unknown.png

Default theme:

https://cdn.discordapp.com/attachments/280102180189634562/891265572422184980/unknown.png

**Comment by AmjadHD** [comment]
Can you try this diff, and send me a screenshot.
```diff
@@ -695,7 +695,8 @@

         {
             "class": "button_control",
-            "min_size": [85, 29],
+            "content_margin": [8, 7],
+            "min_size": [70, 0],
             "layer0.texture": "Theme - One/assets/button.png",
             "layer0.tint": "var(button-bg)",
             "layer0.opacity": 1.0,
```

**Comment by AmjadHD** [comment]
cc @rwols 🙂

**Comment by AmjadHD** [comment]
It should be fixed in the newest version, If it isn't, feel free to reopen the issue.
