### ISSUE TITLE
Weird Icon

### ISSUE THREAD

**Issue by nik736** [AmjadHD/sublime_one_theme#6]
Hi there! Thanks for your work. Appreciate it.

I have the following icon on the right:

<img width="295" alt="Screen Shot 2022-06-27 at 17 20 39" src="https://user-images.githubusercontent.com/1334622/175975780-32ddcd20-b03b-4110-97e0-5eda0b3e1876.png">
 
This looks wrong. Where is it coming from and how to change it?

Thanks!

**Comment by AmjadHD** [comment]
Hi, you're welcomed

* What's the version of ST ? (`Help: About` in the command palette)
* What's your UI Scale (open the console ``ctrl+` ``and scroll to the top)
